development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
  session_key: h8ter_development
  secret: XSheUg1YEEkLX6bSCJYiwgNiV859hL2q
  site_url: http://example.com

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
  session_key: h8ter_test
  secret: 1mF89VtBzDu5doFDnu3pfJHLRJxwaFzH
  site_url: http://example.com
  
production:
  adapter: # mysql
  database: # h8ter
  username: # mysql
  password: # password
  host: # localhost
  session_key: # any string identifying your app
  secret: # at least 32 char random string and should be unique to your installation and kept secret
  site_url: # http://example.com
  site_email: # example <admin@example.com>
  site_name: # h8ter  
  google_analytics: # unique key from http://www.google.com/analytics/
  twitter_user: # h8ter
  twitter_pass: # password
  twitter_source: # http://twitter.com/help/request_source
